#!/usr/bin/env python3
"""Remove specified nodes from maze_data.h and renumber"""

# Nodes to remove (from user request)
nodes_to_remove = {
    6, 7, 8, 9, 10, 11, 12, 13, 20, 21, 22, 23, 24, 25, 26,
    36, 37, 38, 39, 40, 41, 42,  # 42 is connected to 41
    49, 50, 51, 52, 54, 55, 57,
    63, 66, 67, 68, 72, 73,
    81, 82, 83, 84, 85, 86, 87,
    94, 95, 97, 98,
    108, 109, 110, 111, 112, 113,
    121, 122, 123, 124, 125,
    126  # connected to 125 (126 references 107 which connects to 125 area)
}

# Parse original nodes from maze_data.h
original_nodes = []
with open('maze_data.h', 'r') as f:
    for line in f:
        if line.strip().startswith('{') and 'Node' in line:
            # Parse: {gridX, gridY, pixelX, pixelY, {n1, n2, n3, n4}},  // Node N
            parts = line.strip()
            # Extract node data
            data_part = parts.split('//')[0].strip().rstrip(',')
            # Parse the node number from comment
            node_num = int(parts.split('Node')[1].strip())
            original_nodes.append((node_num, data_part))

print(f"Original nodes: {len(original_nodes)}")
print(f"Removing: {len(nodes_to_remove)} nodes")

# Filter out removed nodes and create mapping
kept_nodes = []
old_to_new = {}
new_id = 0

for old_id, data in original_nodes:
    if old_id not in nodes_to_remove:
        old_to_new[old_id] = new_id
        kept_nodes.append((old_id, new_id, data))
        new_id += 1

print(f"Kept nodes: {len(kept_nodes)}")

# Now update the neighbor references in each kept node
def update_neighbors(data_str, mapping):
    """Update neighbor IDs in the data string"""
    # Parse: {gx, gy, px, py, {n1, n2, n3, n4}}
    import re
    # Find the inner neighbors array (last set of braces)
    match = re.search(r'\{(-?\d+),\s*(-?\d+),\s*(-?\d+),\s*(-?\d+)\}\s*\}$', data_str)
    if not match:
        print(f"Warning: could not parse: {data_str}")
        return data_str
    
    neighbors = [int(match.group(i)) for i in range(1, 5)]
    
    # Update each neighbor
    new_neighbors = []
    for n in neighbors:
        if n == -1:
            new_neighbors.append(-1)
        elif n in mapping:
            new_neighbors.append(mapping[n])
        else:
            new_neighbors.append(-1)  # Removed node
    
    # Reconstruct
    new_neighbors_str = ', '.join(str(n) for n in new_neighbors)
    # Find where the neighbors start and replace
    prefix = data_str[:data_str.rfind('{')]
    return prefix + '{' + new_neighbors_str + '}}'
    
    # Reconstruct
    new_neighbors_str = ', '.join(str(n) for n in new_neighbors)
    prefix = data_str[:data_str.rfind('{', 0, data_str.rfind('{'))]
    return prefix + '{' + new_neighbors_str + '}}'

# Generate new header
header = '''// Auto-generated by extract_maze.py (cleaned)
// Removed nodes: ''' + str(sorted(nodes_to_remove)) + '''
// Do not edit manually

#ifndef MAZE_DATA_H
#define MAZE_DATA_H

#include <array>
#include <vector>

struct MazeNodeData {
    int gridX, gridY;           // Grid coordinates
    int pixelX, pixelY;         // Pixel coordinates
    std::array<int, 4> neighbors; // RIGHT, DOWN, LEFT, UP (-1 if none)
};

inline std::vector<MazeNodeData> getMazeNodes() {
    return {
'''

for old_id, new_id, data in kept_nodes:
    updated_data = update_neighbors(data, old_to_new)
    header += f'        {updated_data},  // Node {new_id} (was {old_id})\n'

header += '''    };
}

#endif // MAZE_DATA_H
'''

with open('maze_data_cleaned.h', 'w') as f:
    f.write(header)

print(f"Generated: maze_data_cleaned.h with {len(kept_nodes)} nodes")
